import { Blog } from "./blog";

export const missingHumanLink: Blog = {
  id: "3",
  title: "The missing link of humans - it is still missing!",
  author: "EL Knowledge Management Team",
  summary: "",
  date: "2022-01-03",
  content: [
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "After about a decade of comparative calm, paleoanthropology embarked on another period of swift and prolific discovery, which hasn’t abated yet. The 1960s produced Homo habilis, thought by some to be the missing link between apes and humans, but thought by others not to be a separate species at all. Then came (among many others) Homo ergaster, Homo louisleakeyi, Homo rudolfensis, Homo microcranus, and Homo antecessor, as well as a raft of australopithecines: A.afarensis, A. praegens, A. ramidus, A. walkeri, A. anamensis, and still others. Altogether, some twenty types of hominid are recognized in the literature today. Unfortunately, almost no two experts recognize the same twenty.",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "Some continue to observe the two hominid genera suggested by Howell in 1960, but others place some of the australopithecines in a separate genus called Paranthropus , and still others add an earlier group called Ardipithecus. Some put praegens into Australopithecus and some into a new classification, Homo antiquus, but most don’t recognize praegens as a separate species at all. There is no central authority that rules on these things. The only way a name becomes accepted is by consensus, and there is often very little of that. ",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "A big part of the problem, paradoxically, is a shortage of evidence. Since the dawn of time, several billion human (or humanlike) beings have lived, each contributing a little genetic variability to the total human stock. Out of this vast number, the whole of our understanding of human prehistory is based on the remains, often exceedingly fragmentary, of perhaps five thousand individuals. “You could fit it all into the back of a pickup truck if you didn’t mind how much you jumbled everything up,” Ian Tattersall, the bearded and friendly curator of anthropology at the American Museum of Natural History in New York, replied when I asked him the size of the total world archive of hominid and early human bones.",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "The shortage wouldn’t be so bad if the bones were distributed evenly through time and space, but of course they are not. They appear randomly, often in the most tantalizing fashion. Homo erectus walked the Earth for well over a million years and inhabited territory from the Atlantic edge of Europe to the Pacific side of China, yet if you brought back to life every Homo erectus individual whose existence we can vouch for, they wouldn’t fill a school bus. Homo habilis consists of even less: just two partial skeletons and a number of isolated limb bones. Something as short-lived as our own civilization would almost certainly not be known from the fossil record at all.",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "“In Europe,” Tattersall offers by way of illustration, “you’ve got hominid skulls in Georgia dated to about 1.7 million years ago, but then you have a gap of almost a million years before the next remains turn up in Spain, right on the other side of the continent, and then you’ve got another 300,000-year gap before you get a Homo heidelbergensis in Germany—and none of them looks terribly much like any of the others.” He smiled. “It’s from these kinds of fragmentary pieces that you’re trying to work out the histories of entire species. It’s quite a tall order. We really have very little idea of the relationships between many ancient species—which led to us and which were evolutionary dead ends. Some probably don’t deserve to be regarded as separate species at all.”",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "If we had tens of thousands of skeletons distributed at regular intervals through the historical record, there would be appreciably more degrees of shading. Whole new species don’t emerge instantaneously, as the fossil record implies, but gradually out of other, existing species. The closer you go back to a point of divergence, the closer the similarities are, so that it becomes exceedingly difficult, and sometimes impossible, to distinguish a late Homo erectus from an early Homo sapiens, since it is likely to be both and neither. Similar disagreements can often arise over questions of identification from fragmentary remains—deciding, for instance, whether a particular bone represents a female Australopithecus boisei or a male Homo habilis.",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "With so little to be certain about, scientists often have to make assumptions based on other objects found nearby, and these may be little more than valiant guesses. As Alan Walker and Pat Shipman have drily observed, if you correlate tool discovery with the species of creature most often found nearby, you would have to conclude that early hand tools were mostly made by antelopes.",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "Perhaps nothing better typifies the confusion than the fragmentary bundle of contradictions that was Homo habilis. Simply put, habilis bones make no sense. When arranged in sequence, they show males and females evolving at different rates and in different directions—the males becoming less apelike and more human with time, while females from the same period appear to be moving away from humanness toward greater apeness. Some authorities don’t believe habilis is a valid category at all. Tattersall and his colleague Jeffrey Schwartz dismiss it as a mere “wastebasket species”—one into which unrelated fossils “could be conveniently swept.” Even those who see habilis as an independent species don’t agree on whether it is of the same genus as us or is from a side branch that never came to anything.",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: "Until very recently it was assumed that we were descended from Lucy and the Laetoli creatures, but now many authorities aren’t so sure. Although certain physical features (the teeth, for instance) suggest a possible link between us, other parts of the australopithecine anatomy are more troubling. In their book Extinct Humans, Tattersall and Schwartz point out that the upper portion of the human femur is very like that of the apes but not of the australopithecines; so if Lucy is in a direct line between apes and modern humans, it means we must have adopted an australopithecine femur for a million years or so, then gone back to an ape femur when we moved on to the next phase of our development. They believe, in fact, that not only was Lucy not our ancestor, she wasn’t even much of a walker.",
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      style: "NONE",
      weight: "NORMAL",
      indented: false,
      text: `Conventionally, the Homo line begins with Homo habilis, a creature about whom we know almost nothing, and concludes with us, Homo sapiens (literally “man the thinker”). In between, and depending on which opinions you value, there have been half a dozen other Homo species: Homo ergaster, Homo neanderthalensis, Homo rudolfensis, Homo heidelbergensis, Homo erectus, and Homo antecessor. Homo habilis (“handy man”) was named by Louis Leakey and colleagues in 1964 and was so called because it was the first hominid to use tools, albeit very simple ones. It was a fairly primitive creature, much more chimpanzee than human, but its brain was about 50 percent larger than that of Lucy in gross terms and not much less large proportionally, so it was the Einstein of its day. No persuasive reason has ever been adduced for why hominid brains suddenly began to grow two million years ago. For a long time it was assumed that big brains and upright walking were directly related—that the movement out of the forests necessitated cunning new strategies that fed off of or promoted braininess—so it was something of a surprise, after the repeated discoveries of so many bipedal dullards, to realize that there was no apparent connection between them at all.`,
    },
    {
      type: "PARAGRAPH",
      alignment: "LEFT",
      size: "BASE",
      weight: "NORMAL",
      style: "ITALIC",
      indented: false,
      text: "Credit: Bill Bryson" ,
    },
  ]
}